# Uncomment the next line to define a global platform for your project
# platform :ios, 10.10'

target 'TweetFast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TweetFast


	pod 'Magnet'
	pod 'Fabric'
	pod 'Crashlytics'
pod 'FlatButton'

 

end
